export const SET_RESOURCE = 'SET_RESOURCE';
export const MODIFY_RESOURCE = 'MODIFY_RESOURCE';
export const AUTOINCREMENT_ALL = 'AUTOINCREMENT_ALL';
export const SET_RESOURCE_METRICS = 'SET_RESOURCE_METRICS';
